module.exports = {
	/* Job List Actions */
	RECEIVE_JOBS: 'RECEIVE_JOBS',
	/* Dashboard Actions */
	RECEIVE_COUNT: 'RECEIVE_COUNT',
	RECEIVE_PRICE: 'RECEIVE_PRICE',
	RECEIVE_CATEGORY: 'RECEIVE_CATEGORY',
};
